### ISSUE TITLE
疑似内存泄露.

### ISSUE THREAD

**Issue by Fuck-You-GFW** [Fuck-You-GFW/p2pspider#1]
好些人运行了几个小时, 内存就占满了, 然后自动退出, 怀疑是内存泄露? 也许是TCP 连接数超载? 我得解决解决.

**Comment by luicfer** [comment]
新版本，我试了下，没有这个问题了

**Comment by Fuck-You-GFW** [comment]
合并了完全 ES6 化的PR. 我对 ES6 还不懂. 得看看 ES6 语法, 这个 bug 可能要几天才能修复.
