### ISSUE TITLE
这个软件具体怎么使用？

### ISSUE THREAD

**Issue by tea1111980** [Fuck-You-GFW/p2pspider#11]
按你发的代码说明里面运行了一下，没有任何反应，命令执行成功了。
怎么回事？ 难道还要单独安装BT客户端吗？ 还要X-server ?

**Comment by Fuck-You-GFW** [comment]
我刚更新了下 README.md, **目前只能放在有公网 IP 的主机上执行, 或者路由器设置端口转发.**

**Comment by tea1111980** [comment]
你这还是没有说具体怎么操作啊。。。  note test/index.js 运行之后，没反应啊。 跟不能用，是一回事。

**Comment by Fuck-You-GFW** [comment]
@tea1111980 只有运行在有公网 IP 的主机上, 别人才能把数据发过来. 没反应是因为你运行在内网的主机上, 而外面的主机连不进来, 也就没办法进行数据交流.

**Comment by tea1111980** [comment]
我是公网主机。

**Comment by Fuck-You-GFW** [comment]
@tea1111980  那就见了鬼了. 看看是不是被防火墙拦截了6881端口?

**Comment by tea1111980** [comment]
防火墙我根本就没有开

**Comment by Fuck-You-GFW** [comment]
换端口试试. 

PS: 求助的时候, 加个"感谢"会更好.

**Comment by tea1111980** [comment]
感谢你说了半天，还是没有什么用。

**Comment by tea1111980** [comment]
是不是还需要安装一个BT客户端？
