### ISSUE TITLE
请问怎么保存运行后的输出结果，谢谢！！

### ISSUE THREAD

**Issue by lxlin315** [Fuck-You-GFW/p2pspider#21]
我是一个大白，请问怎么保存运行后的输出结果，谢谢！！

**Comment by Fuck-You-GFW** [comment]
这个需要自己在
```js
p2p.on('metadata', function (metadata) {
    console.log(metadata); // 自行处理数据, 保存到数据库
});
```
里写数据保存代码, 对什么感兴趣, 就保存什么, 不会 Node.js 就自己去学.

`Buffer`类型的, 就`.toString` 即能看到字符串数据. 参见[https://github.com/Fuck-You-GFW/p2pspider/issues/15](https://github.com/Fuck-You-GFW/p2pspider/issues/15)

**Comment by lxlin315** [comment]
好，谢谢
