### ISSUE TITLE
数据保存在哪里

### ISSUE THREAD

**Issue by danran-php** [Fuck-You-GFW/p2pspider#26]
![image](https://cloud.githubusercontent.com/assets/12946324/13658790/620b673e-e6b5-11e5-9188-b85cc8391b25.png)
数据保存在哪里

看不到效果，需要在墙外吗

dht网络 需要一个起始地址和别人通信交流吧

可以自己添加吗

**Comment by Fuck-You-GFW** [comment]
see README.md
