### ISSUE TITLE
在局域网里运行，求思路？

### ISSUE THREAD

**Issue by kaaann** [Fuck-You-GFW/p2pspider#28]
另一个项目nodeDHT可以在局域网运行。
与之比较，也并无大的不同。
沙吹了眼。

请思路？

**Comment by Fuck-You-GFW** [comment]
有很大的区别. 详情请阅读 NAT 这方面的知识.

**Comment by Fuck-You-GFW** [comment]
我刚更新了nodeDHT, 你 `git pull` 后, 再到局域网执行看看, 你就晓得你说的`"与之比较，也并无大的不同。"`其实是你根本没搞懂 DHT 和 NAT 的知识.
