### ISSUE TITLE
想用java实现

### ISSUE THREAD

**Issue by safetys123** [Fuck-You-GFW/p2pspider#31]
想用java实现这样的爬虫，但是没有头绪，想通过QQ请教您一些问题，希望得到一些指点。。。。

**Comment by Fuck-You-GFW** [comment]
自己看协议, QQ 讨论技术也是蛮搞笑的.

**Comment by safetys123** [comment]
什么协议啊？指点下。
QQ讨论技术咋了？？讨论技术还分聊天工具？这样回复来回复去会更有效率？？

**Comment by Fuck-You-GFW** [comment]
请读[提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)
