### ISSUE TITLE
可以讲下知道infohash和对方ip和端口号 怎么下载种子文件吗？

### ISSUE THREAD

**Issue by yahue** [Fuck-You-GFW/p2pspider#43]
新手 想把这个项目换成golang的 其他的都写好了 就差这些了

**Comment by Fuck-You-GFW** [comment]
看相关协议, 或者看我的代码实现.

**Comment by yahue** [comment]
可以给点资料吗？nodejs各种回调 都快看晕了 
看了你的代码 现在知道的是 需要和远程端链接然后是发送握手包 报内容是  BitTorrent protocol [0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x01] +infohash+ 随机id
是这样吗?

**Comment by Fuck-You-GFW** [comment]
http://www.bittorrent.org/beps/bep_0003.html
http://www.bittorrent.org/beps/bep_0009.html
http://www.bittorrent.org/beps/bep_0010.html

先看 bep_0003, 然后 bep_0009 和 bep_0010 混着看.

**Comment by yahue** [comment]
@Fuck-You-GFW 拜谢

**Comment by Fuck-You-GFW** [comment]
README.md 都已经写了相关协议, 为什么还有这么多人问我相关资料? 都不看 README.md 是么?

**Comment by yahue** [comment]
@Fuck-You-GFW 刚入门 一下子看不太懂。。
