### ISSUE TITLE
在家里局域网内的树莓派上安装

### ISSUE THREAD

**Issue by ifengchao** [Fuck-You-GFW/p2pspider#47]
我在家里的树莓派2B上安装了这个包。
Internet公网=====路由器（PPPOE拨号）==== 6881端口UDP转发到内部局域网树莓派。
似乎运行比较缓慢，有时长时间无输出，不太确定是端口转发的原因还是树莓派性能原因，还是其他的原因。
树莓派2代B型，CPU 900MHZ。应该也不至于跑的很慢了。

**Comment by ifengchao** [comment]
另外也曾尝试在阿里云服务器上安装，但运行后一直无输出，除了打印：
UDP Server listening on 0.0.0.0:6881
服务器的firewall是关闭了的。

**Comment by Fuck-You-GFW** [comment]
你要是在国外 VPS 也这样的话, 那可能是你人品的问题哦. :) 你要不试试换个端口?

**Comment by ifengchao** [comment]
是的，我尝试了板瓦工的VPS，在运行过2次后，每次都能成功捕获一些磁力链接，但之后被强制关闭了服务器。提示ip contrack过多可能是一些攻击之类，警告如果第三次再这样将禁用我的服务器。吓的我只好在自己的树莓派上玩了。求推荐能用的，便宜的VPS。

**Comment by Fuck-You-GFW** [comment]
我 p2pspider 用的是[Vutr VPSl](http://www.vultr.com/?ref=6859233) 做测试的, 感觉还蛮不错的, 跑默认参数, 没得什么警告.

**Comment by ifengchao** [comment]
准备换macbook Air在局域网跑一下试试，如果能在局域网抓，方便又节约了再买服务器的money，谢谢推荐哈，回头测测看。

**Comment by ifengchao** [comment]
Vutr VPS 还可以，选了一个日本的节点，运行了一天，大约抓到2000个磁力链接，速度还能提升吗？顺便说一句好多都是小A黄V片。。。但我真的其实主要想抓热门电影的。。。

**Comment by Fuck-You-GFW** [comment]
1, 榨干带宽
2, 读懂代码, 优化爬虫策略.

**Comment by ifengchao** [comment]
不是吧，我的单核CPU/1024M/20GB/Centos7 x64/Tokyo   为毛抓到这么少。。。。

**Comment by Fuck-You-GFW** [comment]
你确保程序真的运行了一天? 之前有个 [BUG](https://github.com/Fuck-You-GFW/p2pspider/issues/45), 会导致程序退出.

**Comment by ifengchao** [comment]
是的，确实运行了一整天，我的SSH一直连着开了一天。用了最新的程序，也差不多是1000-2000个hash。。。
