### ISSUE TITLE
内网转发6881

### ISSUE THREAD

**Issue by ifengchao** [Fuck-You-GFW/p2pspider#48]
我家里用的电信100M光线，PPPOE拨号可以得到公网IP。
在我的linux路由器上执行：
iptables -t nat -A PREROUTING -p udp --dport 6881 -j DNAT --to-destination 192.168.8.168:6881
将访问公网IP的6881端口UDP协议转发到内网192.168.8.168的macbookAir上，macbookAir上再运行node test/index.js 等了10来分钟没抓到包。很想请教下局域网内还要做怎么设置？

**Comment by Fuck-You-GFW** [comment]
换非迅雷 "BT" 工具主导 & 无GFW的国家的 VPS 即可.

**Comment by ifengchao** [comment]
好吧。有空再折腾局域网。谢谢。
