### ISSUE TITLE
运行test问题

### ISSUE THREAD

**Issue by wangtubs** [Fuck-You-GFW/p2pspider#57]
@Fuck-You-GFW 作者居然把之前的问题关掉了https://github.com/Fuck-You-GFW/p2pspider/issues/56，指的重开一个。我用作者推荐的vps vultr测试了下。发现确实没有之前提到的问题。不过我发现用vultr的vps跑dht程序速度很慢，一分钟只得到几个infohash，跟digitalocean家的差远了。难道之前遇到的问题是由于网络或者处理速度的问题？请作者在digitalocean vps上测试下。或者我提供vps让作者测试下。

**Comment by Fuck-You-GFW** [comment]
我用的是vultr ubuntu, 你这跑得这么慢, 肯定用的是 vultr centos 吧? 有个人给我发了邮件, 也是这样的情况, 他换了 ubuntu, 就跟我一样了, 一天一百多万.

**Comment by wangtubs** [comment]
是用的centos 6 64的。不同系统为啥差别这么大呢。而且还不出错?麻烦作者查找下原因

**Comment by Fuck-You-GFW** [comment]
谁知道呢, 我玩不转Linux系统的. 这项目弃坑啦...

**Comment by wangtubs** [comment]
汗。这么好的项目居然弃坑了。

**Comment by Fuck-You-GFW** [comment]
玩腻了, 所以没意思啦. 都玩了两年了, 什么花样都玩过了.

**Comment by wangtubs** [comment]
我测试了ubuntu 16，也会出现错误。跟昨天一样。是不是内存太小了。我用的768M，你的内存多大。

**Comment by Fuck-You-GFW** [comment]
最便宜的那个.

**Comment by wangtubs** [comment]
用node 6.2版测试还会出错。现在改用0.12.14版。多跑一会，有问题再联系你

**Comment by Fuck-You-GFW** [comment]
别联系我啦. 这类问题, 不允许再提 issue 了.
