### ISSUE TITLE
 完全 ES5 化.

### ISSUE THREAD

**Issue by Fuck-You-GFW** [Fuck-You-GFW/p2pspider#6]
Node.js  最新版都不完全支持 ES6, 开发都要那么多辅助性的玩意儿, 太憋屈了. 还是完全 ES5 化, 不混用. 等 Node.js 真的完全支持后, 再 ES6 化.

**Comment by Fuck-You-GFW** [comment]
已完成!

**Comment by welefen** [comment]
可以用 Babel 编译的嘛，环境我都配置好了。执行 npm run compile 就可以了。

**Comment by iugo** [comment]
ES6 的一些语法还是挺方便的.

现在 ECMAScript 更新太快, 这 ES 2016 就要出了吧.

**Comment by Fuck-You-GFW** [comment]
@iugo 彻底完全支持后, 我才考虑.
